{{- if .Values.secretEnabled.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}
data:
{{ toYaml .Values.secrets | indent 3 }}
 # username: #{userename}#
 # password: #{password}#

{{- end }}